param([ValidateSet("draft","telegram-request","telegram-bot","post-instagram","save-package")][string]$Command="telegram-request")
$ErrorActionPreference="Stop"
$Root=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$OutputDir=Join-Path $Root "output"
$DraftPath=Join-Path $OutputDir "draft-powershell.json"
$StatePath=Join-Path $OutputDir "telegram-state-powershell.json"
function Load-Env{ $p=Join-Path $Root ".env"; if(Test-Path $p){ Get-Content $p|%{ if($_ -notmatch '^\s*#' -and $_ -match '='){ $x=$_ -split '=',2; [Environment]::SetEnvironmentVariable($x[0].Trim(),$x[1].Trim(),'Process') }}}}
function E($n,$d=""){ $v=[Environment]::GetEnvironmentVariable($n,'Process'); if([string]::IsNullOrWhiteSpace($v)){return $d}; return $v }
function Clean([string]$t){ if($null -eq $t){return ""}; $c=$t -replace "[\u2018\u2019]","'" -replace "[\u201C\u201D]",'"' -replace "[\u2013\u2014]","-"; return [regex]::Replace($c,"[^\u0009\u000A\u000D\u0020-\u007E]","") }
function Story{ try{ $rss=Invoke-RestMethod -Uri "https://news.google.com/rss/search?q=AI%20technology%20India&hl=en-IN&gl=IN&ceid=IN:en" -TimeoutSec 20; $i=@($rss.rss.channel.item)[0]; if($i){return @{title=[string]$i.title;url=[string]$i.link}} }catch{}; return @{title="New AI tools are changing how creators work";url="https://news.google.com/search?q=AI%20technology"} }
function Text($s){ $k=E "OPENROUTER_API_KEY"; if($k){ try{ $prompt="Create an original social media post from this research note. Do not copy the headline. Return strict JSON with topic, hook, caption, hashtags. Use plain ASCII only. Research note: $($s.title) Source: $($s.url)"; $body=@{model=(E "OPENROUTER_MODEL" "openrouter/free");messages=@(@{role="user";content=$prompt})}|ConvertTo-Json -Depth 6; $r=Invoke-RestMethod -Method Post -Uri "https://openrouter.ai/api/v1/chat/completions" -Headers @{Authorization="Bearer $k";"Content-Type"="application/json";"HTTP-Referer"="https://github.com/chetan638282u/viral-social-publisher";"X-Title"="Viral Social Publisher"} -Body $body -TimeoutSec 45; $j=[regex]::Match([string]$r.choices[0].message.content,"\{[\s\S]*\}").Value|ConvertFrom-Json; return @{topic=Clean $j.topic;hook=Clean $j.hook;caption=Clean $j.caption;hashtags=Clean $j.hashtags} }catch{} }; return @{topic="AI and tech update";hook="This tech shift is worth watching today";caption="This tech shift is worth watching today`n`nA fresh signal from today's tech news: $($s.title)`n`nSource: $($s.url)";hashtags="#AI #Technology #India #ViralBriefIndia #TechNews"} }
function Image($hook,$path){ Add-Type -AssemblyName System.Drawing; if(Test-Path $path){Remove-Item $path -Force}; New-Item -ItemType Directory -Force -Path (Split-Path -Parent $path)|Out-Null; $b=New-Object Drawing.Bitmap 1080,1080; $g=[Drawing.Graphics]::FromImage($b); $g.Clear([Drawing.Color]::FromArgb(12,15,22)); $a=New-Object Drawing.SolidBrush ([Drawing.Color]::FromArgb(0,220,190)); $w=New-Object Drawing.SolidBrush ([Drawing.Color]::White); $m=New-Object Drawing.SolidBrush ([Drawing.Color]::FromArgb(180,190,205)); $f1=New-Object Drawing.Font "Arial",58,([Drawing.FontStyle]::Bold); $f2=New-Object Drawing.Font "Arial",28; $g.FillRectangle($a,0,0,1080,28); $g.DrawString("VIRAL BRIEF INDIA",$f2,$m,80,90); $g.DrawString($hook,$f1,$w,(New-Object Drawing.RectangleF 80,250,920,520)); $g.DrawString("AI | Tech | Gaming | Culture",$f2,$a,80,880); $g.DrawString("@viralbriefindia",$f2,$m,80,930); $b.Save($path,[Drawing.Imaging.ImageFormat]::Png); $g.Dispose(); $b.Dispose() }
function New-Draft{ New-Item -ItemType Directory -Force -Path $OutputDir|Out-Null; $s=Story; $p=Text $s; $img=Join-Path $OutputDir "post-powershell.png"; Image $p.hook $img; $d=[ordered]@{topic=$p.topic;hook=$p.hook;caption=$p.caption;hashtags=$p.hashtags;image_path=$img;source_title=$s.title;source_url=$s.url;created_at=(Get-Date).ToString("o")}; $d|ConvertTo-Json -Depth 5|Set-Content $DraftPath -Encoding UTF8; return $d }
function T($method,$body){ $tok=E "TELEGRAM_BOT_TOKEN"; Invoke-RestMethod -Method Post -Uri "https://api.telegram.org/bot$tok/$method" -Body $body -TimeoutSec 60 }
function TFile($method,$path,$field,$body){ Add-Type -AssemblyName System.Net.Http; $tok=E "TELEGRAM_BOT_TOKEN"; $c=New-Object System.Net.Http.HttpClient; $mp=New-Object System.Net.Http.MultipartFormDataContent; foreach($k in $body.Keys){$mp.Add((New-Object System.Net.Http.StringContent([string]$body[$k])),$k)}; $st=[IO.File]::OpenRead((Resolve-Path $path)); try{$fc=New-Object System.Net.Http.StreamContent($st); $mp.Add($fc,$field,(Split-Path -Leaf $path)); $res=$c.PostAsync("https://api.telegram.org/bot$tok/$method",$mp).Result; $txt=$res.Content.ReadAsStringAsync().Result; if(!$res.IsSuccessStatusCode){throw $txt}; return $txt|ConvertFrom-Json}finally{$st.Dispose();$c.Dispose();$mp.Dispose()} }
function Request{ $d=New-Draft; $chat=E "TELEGRAM_CHAT_ID"; $kb=@{inline_keyboard=@(@(@{text="Save package";callback_data="save_latest"},@{text="Direct post";callback_data="post_latest"}),@(@{text="Reject";callback_data="reject_latest"}))}|ConvertTo-Json -Compress -Depth 5; T "sendMessage" @{chat_id=$chat;text="Approval needed`n`nHook: $($d.hook)`n`nCaption:`n$($d.caption)`n`n$($d.hashtags)";reply_markup=$kb}|Out-Null; TFile "sendPhoto" $d.image_path "photo" @{chat_id=$chat;caption="Preview image draft"}|Out-Null; @{status="pending";last_update_id=0;draft_path=$DraftPath}|ConvertTo-Json|Set-Content $StatePath; Write-Host "Telegram approval request sent." }
function Package($chat){ $d=Get-Content -Raw $DraftPath|ConvertFrom-Json; $dir=Join-Path $OutputDir "manual-upload-package"; New-Item -ItemType Directory -Force -Path $dir|Out-Null; $cap=Join-Path $dir "caption.txt"; $img=Join-Path $dir "post-image.png"; "Caption:`n$($d.caption)`n`nHashtags:`n$($d.hashtags)`n`nSource:`n$($d.source_url)"|Set-Content $cap -Encoding UTF8; Copy-Item $d.image_path $img -Force; T "sendMessage" @{chat_id=$chat;text="Saved package ready. Caption:`n`n$($d.caption)`n`n$($d.hashtags)"}|Out-Null; TFile "sendPhoto" $img "photo" @{chat_id=$chat;caption="Preview image"}|Out-Null; TFile "sendDocument" $img "document" @{chat_id=$chat;caption="Download this image for manual upload"}|Out-Null; TFile "sendDocument" $cap "document" @{chat_id=$chat;caption="Caption and hashtags text file"}|Out-Null }
function Upload($path){ $gt=E "GITHUB_TOKEN"; if(!$gt){ $r=& curl.exe --ssl-no-revoke --silent --show-error --connect-timeout 10 --max-time 60 -F "reqtype=fileupload" -F "fileToUpload=@$path" "https://catbox.moe/user/api.php"; if($LASTEXITCODE -ne 0 -or $r -notmatch '^https://'){throw "Could not create public media URL: $r"}; return $r.Trim() }; throw "GitHub media upload is not enabled in compact runner." }
function IGPost($uri,$body){ try{return Invoke-RestMethod -Method Post -Uri $uri -Body $body -TimeoutSec 60}catch{ $det=$_.Exception.Message; if($_.Exception.Response){try{$rd=New-Object IO.StreamReader($_.Exception.Response.GetResponseStream()); $bt=$rd.ReadToEnd(); if($bt){$det=$bt -replace '"access_token"\s*:\s*"[^"]+"','"access_token":"[redacted]"'}}catch{}}; throw "Instagram API error: $det" } }
function PostIG{ $d=Get-Content -Raw $DraftPath|ConvertFrom-Json; $tok=E "INSTAGRAM_ACCESS_TOKEN" (E "META_ACCESS_TOKEN"); $id=E "INSTAGRAM_BUSINESS_ACCOUNT_ID"; $ver=E "META_GRAPH_VERSION" "v25.0"; if(!$tok -or !$id){throw "Instagram token and account ID are required."}; $url=E "PUBLIC_IMAGE_URL"; if(!$url){$url=Upload $d.image_path}; $cap="$($d.caption)`n`n$($d.hashtags)"; $cr=IGPost "https://graph.instagram.com/$ver/$id/media" @{image_url=$url;caption=$cap;access_token=$tok}; $pub=IGPost "https://graph.instagram.com/$ver/$id/media_publish" @{creation_id=$cr.id;access_token=$tok}; return @{platform="instagram";status="posted";response=$pub} }
function Bot{ $offset=0; if(Test-Path $StatePath){$s=Get-Content -Raw $StatePath|ConvertFrom-Json; $offset=[int]$s.last_update_id+1}; while($true){ $u=T "getUpdates" @{timeout=30;offset=$offset}; foreach($x in @($u.result)){ $offset=[int]$x.update_id+1; if($x.callback_query){ $c=$x.callback_query; $chat=$c.message.chat.id; if($c.data -eq "reject_latest"){T "answerCallbackQuery" @{callback_query_id=$c.id;text="Rejected. Nothing posted."}|Out-Null}elseif($c.data -eq "save_latest"){T "answerCallbackQuery" @{callback_query_id=$c.id;text="Saved package sent."}|Out-Null; Package $chat}elseif($c.data -eq "post_latest"){T "answerCallbackQuery" @{callback_query_id=$c.id;text="Posting to Instagram..."}|Out-Null; T "sendMessage" @{chat_id=$chat;text="Posting to Instagram now. I will send the result here."}|Out-Null; try{$r=PostIG; T "sendMessage" @{chat_id=$chat;text="Instagram result:`n$($r|ConvertTo-Json -Depth 5)"}|Out-Null}catch{T "sendMessage" @{chat_id=$chat;text="Direct post failed:`n$($_.Exception.Message)"}|Out-Null}}}; @{last_update_id=[int]$x.update_id}|ConvertTo-Json|Set-Content $StatePath } } }
Load-Env
switch($Command){"draft"{New-Draft|ConvertTo-Json -Depth 5};"telegram-request"{Request};"telegram-bot"{Bot};"post-instagram"{PostIG|ConvertTo-Json -Depth 5};"save-package"{Package (E "TELEGRAM_CHAT_ID")}}
